Install userlists only with new enough updater
Disable listing of userlists' packages in old updater. Some packages use
the Provides header and break the old updater, so we don't list them
there and just update the updater itself first.

diff --git a/compile_fw b/compile_fw
--- a/compile_fw
+++ b/compile_fw
@@ -249,15 +249,17 @@ echo Install $(sed -n 's|Package: \(.*\)|"\1"|p' $OPKG_STATUS | egrep -v '"updat
 [ \! -f "lists/base_add.$TARGET_BOARD" ] || echo Install $(cat "lists/base_add.$TARGET_BOARD" | sed 's|^\([^#]\+\)$|"\1"|') " { critical = true }" >> base.lua
 mv base.lua $PUB_BIN_DIR/lists
 for i in lists/*.list; do
-	[ "$i" = lists/base.list ] || rm -f $PUB_BIN_DIR/lists/$(basename $i .list).lua
-	echo -n "Install" >> $PUB_BIN_DIR/lists/$(basename $i .list).lua
+	LUA="$(basename $i .list).lua"
+	[ "$i" = lists/base.list ] || echo 'if features and features.provides then' > $PUB_BIN_DIR/lists/"$LUA"
+	echo -n "  Install" >> $PUB_BIN_DIR/lists/"$LUA"
 	grep -h -v CONFIG_ "$i" "${i/%list/${TARGET_BOARD}}" 2> /dev/null | grep . | grep -v '^#' | while read pkg; do
-		echo -n " \"$pkg\"" >> $PUB_BIN_DIR/lists/$(basename $i .list).lua
+		echo -n " \"$pkg\"" >> $PUB_BIN_DIR/lists/"$LUA"
 	done
-	echo " { ignore = { 'missing' } }" >> $PUB_BIN_DIR/lists/$(basename $i .list).lua
-	sed -i '/^Install[[:blank:]]*$/ d' $PUB_BIN_DIR/lists/$(basename $i .list).lua
+	echo " { ignore = { 'missing' } }" >> $PUB_BIN_DIR/lists/"$LUA"
+	sed -i '/^  Install[[:blank:]]*$/ d' $PUB_BIN_DIR/lists/"$LUA"
+	[ "$i" = lists/base.list ] || echo 'end' > $PUB_BIN_DIR/lists/"$LUA"
 	if [ -f "$HOME"/mime.key ]; then
-		staging_dir/host/bin/usign -S -m $PUB_BIN_DIR/lists/$(basename $i .list).lua -s "$HOME"/mime.key
+		staging_dir/host/bin/usign -S -m $PUB_BIN_DIR/lists/"$LUA" -s "$HOME"/mime.key
 	fi
 done
 for i in lists/*.lua; do
